app/models/__init__.py
"""Models package"""

app/models/user.py
from app.extensions import db
from app.services.github import GitHub

class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    avatar_url = db.Column(db.String(80), nullable=True)
    github_id = db.Column(db.Integer(), nullable=True)

    def __init__(self, username, avatar_url, github_id):
        self.username = username
        self.avatar_url = avatar_url
        self.github_id = github_id

    @staticmethod
    def find_or_create_from_token(access_token):
        data = GitHub.get_user_from_token(access_token)

        """Find existing user or create new User instance"""
        instance = User.query.filter_by(username=data['login']).first()

        if not instance:
            instance = User(data['login'], data['avatar_url'], data['id'])
            db.session.add(instance)
            db.session.commit()

        return instance

    def __repr__(self):
        return "<User: {}>".format(self.username)

app/__init__.py
"""Main application package"""

app/app.py
import os

from flask import Flask, render_template
from . import settings, controllers, models
from .extensions import db

project_dir = os.path.dirname(os.path.abspath(__file__))

def create_app(config_object=settings):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config_object)

    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app

def register_extensions(app):
    """Register Flask extensions."""
    db.init_app(app)

    with app.app_context():
        db.create_all()
    return None

def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(controllers.home.blueprint)
    app.register_blueprint(controllers.auth.blueprint)
    app.register_blueprint(controllers.tutorial.blueprint)
    return None

def register_errorhandlers(app):
    """Register error handlers."""
    @app.errorhandler(401)
    def internal_error(error):
        return render_template('401.html'), 401

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('404.html'), 404

    @app.errorhandler(500)
    def internal_error(error):
        return render_template('500.html'), 500

    return None

app/controllers/__init__.py
"""Controllers package"""
from . import auth
from . import tutorial
from . import home

app/controllers/auth.py
# -*- coding: utf-8 -*-
import functools, json, requests

from flask import flash, redirect, render_template, request
from flask import Blueprint, session, url_for, g

from app.models.user import User
from app.settings import GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET
from app.services.github import GitHub

blueprint = Blueprint('auth', __name__, url_prefix='/auth')

@blueprint.route('/login/github')
def githubLogin():
    github = GitHub(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET)
    return redirect(github.authorization_url(scope='public_repo'))

@blueprint.route('/callback/github', methods=('GET', 'POST'))
def githubCallback():
    if 'code' not in request.args:
        return '', 500

    # Fetch user from GitHub OAuth and store in session
    github = GitHub(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET)
    access_token = github.get_token(request.args['code'])

    if access_token is None:
        flash('Could not authorize your request. Please try again.', 'danger')
        return '', 404

    user = User.find_or_create_from_token(access_token)

    session['access_token'] = access_token
    session['user_id'] = user.id

    return redirect(url_for('home.index'))

@blueprint.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('home.index'))

@blueprint.before_app_request
def get_current_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(id=user_id).first()

app/controllers/home.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

blueprint = Blueprint('home', __name__)

@blueprint.route('/')
def index():
    return render_template('home/index.html')

app/controllers/tutorial.py
# -*- coding: utf-8 -*-
from flask import redirect, render_template, request
from flask import g, Blueprint, flash, url_for, session

from app.services.github import GitHub

blueprint = Blueprint('tutorial', __name__, url_prefix='/tutorial')

@blueprint.route('/requesting')
def requesting():
    search = request.args.get('query', '')
    if not 'access_token' in session:
        flash('This tutorial needs an authenticated user to make the request. Please sign in with your GitHub account.', 'danger')
        return render_template('tutorial/requesting.html')

    github = GitHub(access_token=session['access_token'])
    results1 = github.get('/user/starred')
    results2 = github.get('/search/repositories', { 'q': search } )
    results2 = results2.get('items', [])

    return render_template('tutorial/requesting.html',
        tutorial1 = results1[:5],
        tutorial2 = results2[:5],
        query = search
    )

@blueprint.route('/star', methods=['POST'])
def star():
    repo = request.form['full_name']

    if not 'access_token' in session:
        flash('Please sign in with your GitHub account.', 'danger')
        return redirect(url_for('github.fetching'))

    github = GitHub(access_token=session['access_token'])
    github.delete('/user/starred/' + repo)

    return redirect(url_for('tutorial.fetching'))

app/services/__init__.py
"""Services package"""

app/templates/401.html
{% extends "layouts/layout.html" %}

{% block content %}
  <div class="container py-5 my-5 text-muted text-center">
    <h1 class="h5">This isn't the page you are looking for.</h1>
    <p>We couldn't find this page. Please check your URL or go back home.<p>
    <a href="/" class="btn btn-primary">Go back home</a>
  </div>
{% endblock %}

app/templates/home/index.html
{% extends "layouts/layout.html" %}

{% block header %}
<div class="bg-gray-light border-bottom border-gray-light">
  <div class="container text-center py-5 mb-4">
    <img src="{{ url_for('static', filename='img/logo.png') }}" class="w-100" style="max-width:120px;" />
    <div class="mt-3 mb-4">
      <h1 class="h1 mb-0">Hackathon Flask Starter</h1>
      <h2 class="h4 text-gray font-weight-light">Build your hackathon project faster.</h2>
    </div>
    <a class="btn btn-primary mt-2" href="https://github.com/MLH/mlh-hackathon-flask-starter">
      Check the Docs
    </a>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="text-gray-light text-center py-5 my-5">
  <p class="lead">Edit <code>controllers/</code> to update how to receive and reply to requests.</p>
  <p class="lead">Edit <code>templates/</code> to update the layout and styling.</p>
  <p class="lead">Edit <code>models/</code> to update how the data is stored.</p>
</div>
{% endblock %}

app/templates/layouts/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>My Hackathon Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" >
    <link rel="stylesheet" href="{{ url_for('static', filename='css/colors.css') }}" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  </head>
  <body>
    {% include "partials/header.html" %}

    {% include "partials/flash.html" %}

    {% block header %}{% endblock %}

    {% block content %}{% endblock %}

    {% include "partials/footer.html" %}

    <!-- Scripts for Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/partials/flash.html
{% for category, message in get_flashed_messages(with_categories=true) %}
  <div class="alert alert-{{ category if category != None else 'danger' }} mb-0 rounded-0">
    <div class="container">
      {{ message }}
    </div>
  </div>
{% endfor %}

app/templates/partials/footer.html
{% block footer %}
  {# Add a global footer here if you like #}
{% endblock %}

app/templates/partials/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-gray-dark text-white">
  <div class="container">
    <a class="text-white link-reset text-inherit pr-3" href="/">
      My Hackathon Project
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tutorials
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('tutorial.requesting' )}}">Requesting Data</a>
          </div>
        </li>
        {% if g.user %}
          <li class="nav-item p-2 pr-3">
            <img src="{{ g.user['avatar_url'] }}" class='rounded mr-2' style='width:24px;height:24px;'/>
            {{ g.user['username'] }}
          </li>
          <li class="nav-item">
            <a class="nav-link text-inherit" href="{{ url_for('auth.logout') }}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link text-inherit" href="{{ url_for('auth.githubLogin') }}">
              Login with GitHub
            </a>
          </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>

app/templates/tutorial/base.html
{% extends "layouts/layout.html" %}

{% block header %}
  <div class="bg-dark text-light">
    <div class="container text-center py-5 mb-4">
      <img src="{{ url_for('static', filename='img/logo.png') }}" class="w-100" style="max-width:120px;" />
      <div class="mt-3 mb-4">
        <h1 class="h1 mb-0">{% block title %}{% endblock %}</h1>
        <h2 class="h4 font-weight-light text-gray-light">{% block subtitle %}{% endblock %}</h2>
      </div>
      <a class="btn btn-outline-light" href="https://developer.github.com/v3/">Check GitHub API</a>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container py-5 my-5" style="max-width: 980px;">
    {% block container %}{% endblock %}
  </div>
{% endblock %}

app/templates/tutorial/repo.html
{% macro render_repo(item, loop) %}
  <div class="border-bottom {{ 'border-top' if loop.first }}">
    <div class="d-flex flex-column m-3">
      <a class="text-blue" href="{{ item['html_url'] }}">
        {{ item["owner"]["login"] }} / <b>{{ item["name"] }}</b>
      </a>
      <small class="text-gray">{{ item["description"] }}</small>
      <div class="mt-2">
        <small class="text-gray mr-3">{{ item["language"] }}</small>
        <small class="text-gray mr-3">{{ item["stargazers_count"] }} Stars</small>
        <small class="text-gray mr-3">{{ item["forks_count"] }} Forks</small>
      </div>
    </div>
  </div>
{% endmacro %}

app/templates/tutorial/requesting.html
{% extends "tutorial/base.html" %}
{% from "tutorial/repo.html" import render_repo with context %}

{% block title %}Requesting Data{% endblock %}
{% block subtitle %}Learn how to retrieve data from GitHub.{% endblock %}

{% block container %}
  <h4 class="py-1 m-0">GitHub API</h4>
  <p class="mb-5">GitHub provides a way to request and interact with data on its platform. This makes it possible to use GitHub data in your application. For example, you can see all your favorite GitHub projects or show what code you are working. This interaction is done through a interface called an API. We provided examples of using GitHub's API to help you get started.</a>

  <div class="border rounded p-5 mb-5">
    <h5 class="py-1 m-0">Retrieving your starred projects</h5>
    <p>You can retrieve your starred projects on GitHub using the <code>/user/starred</code> endpoint. Within this starter project, you can also use the <code>services/github.py</code> module, which makes it easier to make an authenticated request.<p>
    <p>A GET request to the <code>/user/starred</code> endpoint using the <code>github.py</code> module would follow this format:</p>
    <pre class="bg-light rounded"><code>
      github = GitHub(access_token=session['access_token'])
      results = github.get('/user/starred')
    </code></pre>
    <p class="mt-4">As a result, you will see your starred repositories below:</p>
    {% if tutorial1|length == 0 %}
      <div class="bg-light rounded p-5 text-center text-muted">
        {% if g.user %}
          <p class="m-4">You haven't starred any repositories on GitHub yet. You can star <a href="https://github.com/MLH/mlh-hackathon-flask-starter">this project here</a>.</p>
        {% else %}
          <p class="m-4">This example requires an authenticated user. Please log in to see your starred repositories.</p>
        {% endif %}
      </div>
    {% endif %}

    {% for item in tutorial1 %}
      {{ render_repo(item, loop) }}
    {% endfor %}
  </div>

  <div class="border rounded p-5">
    <h5 class="py-1 m-0">Searching GitHub</h5>
    <p>The endpoint for searching GitHub projects is located at <code>/search/repositories</code>. You can use this endpoint to find projects on GitHub. Within this starter project, you also can use the <code>services/github.py</code> module, which makes it easier to make an authenticated request.
    <p>A GET request to the <code>/search/repositories</code> endpoint using the <code>github.py</code> module would follow this format:</p>
    <pre class="bg-light rounded"><code>
      github = GitHub(access_token=session['access_token'])
      results = github.get('/search/repositories')
    </code></pre>
    <p class="mt-4">As a result, you should be able to search for GitHub projects below:</p>
    <div class="text-center mx-auto mb-3">
      <form action="{{ url_for('tutorial.requesting') }}" method="get" class="d-flex">
        <input name="query" class="form-control form-control-sm" value="{{ query }}" placeholder="Search for repos" />
        <button type="submit" class="btn btn-primary btn-sm ml-1">Search</button>
      </form>
    </div>

    {% if tutorial2|length == 0 %}
      <div class="rounded bg-light p-5 text-center text-muted">
        {% if g.user %}
          {% if query or query|length == 0 %}
            <p class="m-4">You can use the search bar above to find new projects.</p>
          {% else %}
            <p class="m-4">Cannot find a repository that matches that input. Please try again.</p>
          {% endif %}
        {% else %}
          <p class="m-4">Please sign in to use the search functionality.</p>
        {% endif %}
      </div>
    {% endif %}

    {% for item in tutorial2 %}
      {{ render_repo(item, loop) }}
    {% endfor %}
  </div>

{% endblock %}